#pragma once

#define OLED_UPDATE_INTERVAL 200

/* RGB LED PIN IS USED FOR HANDEDNESS */
#define SPLIT_HAND_PIN D3

/* TAPPING CONFIG */
#define TAPPING_TERM 160
#define TAPPING_TOGGLE 2
#define TAPPING_FORCE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define NO_USB_STARTUP_CHECK

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
