#pragma once

/* OLED SETTINGS */
#define OLED_UPDATE_INTERVAL 200
#define OLED_BRIGHTNESS 128
#define OLED_TIMEOUT 15000
#define OLED_FADE_OUT
#define OLED_SCROLL_TIMEOUT (OLED_TIMEOUT / 2)

/* RGB LED PIN IS USED FOR HANDEDNESS */
#define SPLIT_HAND_PIN D3

/* TAPPING CONFIG */
#define TAPPING_TERM 160
#define TAPPING_TOGGLE 2
#define QUICK_TAP_TERM 0
#define IGNORE_MOD_TAP_INTERRUPT
// #define ACTION_DEBUG
// #define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

// #define NO_USB_STARTUP_CHECK

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

/* SPLIT KEYBOARD */
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_WATCHDOG_ENABLE
#define SERIAL_DEBUG

#define RGBLIGHT_LIMIT_VAL 255
#define RGBLIGHT_DEFAULT_HUE 35
#define RGBLIGHT_DEFAULT_VAL RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_MOOD
#define RGB_DISABLE_WHEN_USB_SUSPENDED

#define GP9 9U
#define AUDIO_PIN GP9
#define AUDIO_PWM_DRIVER PWMD4
#define AUDIO_PWM_CHANNEL 2U
