OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
MUSIC_ENABLE = no

DEBOUNCE_TYPE = asym_eager_defer_pk
DEBUG_MATRIX_SCAN_RATE_ENABLE = yes

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812
WS2812_DRIVER = vendor
LTO_ENABLE = yes

# AUDIO_ENABLE = yes
# AUDIO_DRIVER = pwm_hardware
