# MCU name
MCU = RP2040

OPT_DEFS += -Os -gdwarf-4 
LTO_ENABLE = yes
ALLOW_WARNINGS = yes
SPLIT_KEYBOARD = yes
# EEPROM_DRIVER  = spi
KEYBOARD_SHARED_EP = no
SERIAL_DRIVER = pio
CONSOLE_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812
WS2812_DRIVER = pio
OLED_ENABLE = no
OLED_DRIVER = SSD1306
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
RAW_ENABLE = yes
