#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(RGB_TOG, RGB_MODE_RGBTEST, KC_TAB, KC_Q),
    [1] = LAYOUT(KC_ESC, KC_1, KC_TAB, KC_Q),
    [2] = LAYOUT(KC_ESC, KC_1, KC_TAB, KC_Q),
    [3] = LAYOUT(KC_ESC, KC_1, KC_TAB, KC_Q),
};
